### PR TITLE
Recognition update

### PR DESCRIPTION
**Pull request by ToMadoRe**

### CODE REVIEW

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
#11 probably fixed now with V4R 1.1.0

**Comment by marc-hanheide** [comment]
there was `object_classifer` instead of `object_classifier` in various places in this...

**Comment by marc-hanheide** [comment]
OK, there are other problems in this as well... Please check it @ToMadoRe:

```
/opt/ros/indigo/include/v4r/rendering/depthmapRenderer.h:34:23: fatal error: glm/glm.hpp: No such file or directory
 #include <glm/glm.hpp>
                       ^ 
```

from https://lcas.lincoln.ac.uk/jenkins/job/pr-indigo-v4r_ros_wrappers/19/console

Looks again missing more deps...

**Comment by ToMadoRe** [comment]
why does this happen? There is libglm-dev as build dependency in the v4r package. Do we also have to include this in v4r_ros_wrappers?

**Comment by marc-hanheide** [comment]
Because it is a _build_ dependency in `V4R`. Which obviously means it is installed when you build V4R, not when you just use it. Like you don't need a compiler when you _run_ a programme. If you need the headers of libglm in the wrappers, you need to make it a dependency again. Alternatively, you could make `libglm-dev` a `<run_depend>` in V4R as you did with most `*-dev` deps in https://github.com/strands-project/v4r/blob/master/package.xml already.

**Comment by taketwo** [comment]
Actually, we should ask Simon to refactor rendering classes and use PIMPL idiom to hide dependencies that are implementation details. GLM, GLEW, GLFW are all not a part of the public interface and, as such, should not be required to compile user code.

**Comment by ToMadoRe** [comment]
retest this please

**Comment by marc-hanheide** [comment]
I think this was too early, as the build chain is still running... this test will still use the old version of V4R as jenkins is currently still processing...

**Comment by marc-hanheide** [comment]
NOW, we can try ;-)

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
BTW, @ToMadoRe, I managed to fix the bloom release procedure so it know accepts your name in the ChangeLogs correctly. The way python handles unicode is puzzling.

**Comment by marc-hanheide** [comment]
Yeah!

**Comment by marc-hanheide** [comment]
I already triggered a re-release of this after this successful build.

**Pull request merged**
