### PR TITLE
add tutorial

### PR DESCRIPTION
**Pull request by ToMadoRe**

### CODE REVIEW

**Comment by ToMadoRe** [comment]
@marc-hanheide Are you okay with adding this (Lamor15 - summer school) tutorial directly in here? This also includes images and so can slightly increase download time.

**Comment by marc-hanheide** [comment]
No problem but why? It's publicly available anyway. I think the wiki is more user friendly. But your call. But if you copy here please remove from lamor and link it from there. Or simply link it from this readme, I'd suggest.

**Comment by ToMadoRe** [comment]
The main problem is that I don't have permissions to change the lamor tutorial and the interfaces have changed slightly since then. Also I thought it's more obvious that you can find the up-to-date version directly inside the repo and not at a page from an external repo named something with 2015. But I am fine either way - I would just need permission then.

**Comment by marc-hanheide** [comment]
OK, makes sense. I gave you write permissions to lamor wiki. Please update the tutorial to link here then. Thanks.

**Pull request merged**
