### PR TITLE
fixed namespace and include issues to fit V4R Version 1.0.11

### PR DESCRIPTION
**Pull request by ToMadoRe**

### CODE REVIEW

**Comment by jontromanab** [comment]
I am sorry but there is still some problems. I have tried with the V4R 1.0.11 and V4R_ros_wrappers 0.0.6. Here is the errors I am receiving while building v4r_ros_wrapper:

Linking CXX executable /root/catkin_ws/devel/lib/singleview_object_recognizer/recognition_service
Linking CXX executable /root/catkin_ws/devel/lib/multiview_object_recognizer/multiview_object_recognizer_node
Linking CXX executable /root/catkin_ws/devel/lib/camera_tracker/camera_tracker_service
CMakeFiles/multiview_object_recognizer_node.dir/src/multiview_object_recognizer_ros.cpp.o: In function `v4r::multiviewGraphROS::initializeMV(int, char**)':
/root/catkin_ws/src/v4r_ros_wrappers-master/multiview_object_recognizer/src/multiview_object_recognizer_ros.cpp:243: undefined reference to`v4r::SingleViewRecognizer::initialize()'
/root/catkin_ws/src/v4r_ros_wrappers-master/multiview_object_recognizer/src/multiview_object_recognizer_ros.cpp:252: undefined reference to `v4r::MultiviewRecognizer::printParams(std::ostream&)'
CMakeFiles/multiview_object_recognizer_node.dir/src/multiview_object_recognizer_ros.cpp.o: In function`v4r::multiviewGraphROS::recognizeROS(recognition_srv_definitions::recognizeRequest_std::allocator<void >&, recognition_srv_definitions::recognizeResponse_std::allocator<void >&)':
/root/catkin_ws/src/v4r_ros_wrappers-master/multiview_object_recognizer/src/multiview_object_recognizer_ros.cpp:151: undefined reference to `v4r::MultiviewRecognizer::recognize(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> const>, std::string const&, std::vector<float, std::allocator<float> > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [/root/catkin_ws/devel/lib/multiview_object_recognizer/multiview_object_recognizer_node] Error 1
make[1]: *** [v4r_ros_wrappers-master/multiview_object_recognizer/CMakeFiles/multiview_object_recognizer_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/recognition_service.dir/src/recognizer_ros.cpp.o: In function`v4r::RecognizerROS::retrainROS(recognition_srv_definitions::retrain_recognizerRequest_std::allocator<void >&, recognition_srv_definitions::retrain_recognizerResponse_std::allocator<void >&)':
/root/catkin_ws/src/v4r_ros_wrappers-master/singleview_object_recognizer/src/recognizer_ros.cpp:23: undefined reference to `v4r::SingleViewRecognizer::retrain(std::vector<std::string, std::allocator<std::string> > const&)'
CMakeFiles/recognition_service.dir/src/recognizer_ros.cpp.o: In function`v4r::RecognizerROS::initialize(int, char*_)':
/root/catkin_ws/src/v4r_ros_wrappers-master/singleview_object_recognizer/src/recognizer_ros.cpp:234: undefined reference to `v4r::SingleViewRecognizer::initialize()'
/root/catkin_ws/src/v4r_ros_wrappers-master/singleview_object_recognizer/src/recognizer_ros.cpp:237: undefined reference to`v4r::SingleViewRecognizer::printParams(std::ostream&) const'
CMakeFiles/recognition_service.dir/src/recognizer_ros.cpp.o: In function `v4r::RecognizerROS::recognizeROS(recognition_srv_definitions::recognizeRequest_<std::allocator<void> >&, recognition_srv_definitions::recognizeResponse_<std::allocator<void> >&)':
/root/catkin_ws/src/v4r_ros_wrappers-master/singleview_object_recognizer/src/recognizer_ros.cpp:161: undefined reference to`v4r::SingleViewRecognizer::recognize()'
collect2: error: ld returned 1 exit status
make[2]: *_\* [/root/catkin_ws/devel/lib/singleview_object_recognizer/recognition_service] Error 1
make[1]: **\* [v4r_ros_wrappers-master/singleview_object_recognizer/CMakeFiles/recognition_service.dir/all] Error 2
/opt/ros/indigo/lib/libv4r_features.so.1.0.0: undefined reference to `pcl::search::KdTreepcl::PointXYZ::KdTree(bool)'
collect2: error: ld returned 1 exit status
make[2]: **\* [/root/catkin_ws/devel/lib/camera_tracker/camera_tracker_service] Error 1
make[1]: **\* [v4r_ros_wrappers-master/camera_tracker/CMakeFiles/camera_tracker_service.dir/all] Error 2
make: **\* [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by marc-hanheide** [comment]
Hmm, I'm not sure. Maybe @ToMadoRe can help here, but I do know that the build of the Ubuntu packages succeeded, so can't you just use those? See https://github.com/strands-project-releases/strands-releases/wiki and then all you'd have to do is `sudo apt-get install ros-indigo-v4r` etc?

**Comment by ToMadoRe** [comment]
That's strange. These definitions are there in the recognition module. Are you sure you are linking against the right library and not against some other installed version of V4R? Can you `locate libv4r_recognition.so` and maybe check if these definitions are there, e.g. `nm -C /path/to/libv4r_recognition.so | grep printParams`

**Comment by jontromanab** [comment]
Thank you very much @ToMadoRe  and @marc-hanheide ....I think it is working now.

**Pull request merged**
