### PR TITLE
Fix warnings and headers1

### PR DESCRIPTION
**Pull request by ToMadoRe**

### CODE REVIEW

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
OK, it got pretty far:

```
[ 87%] Building CXX object monitored_vcs/object_classifier/CMakeFiles/object_classifier_node.dir/src/global_nn_classifier_ros.cpp.o
/var/lib/jenkins/workspace/pr-indigo-v4r_ros_wrappers/monitored_vcs/object_classifier/src/global_nn_classifier_ros.cpp:20:41: fatal error: v4r/recognition/mesh_source.h: No such file or directory
 #include <v4r/recognition/mesh_source.h>
```

**Comment by marc-hanheide** [comment]
actually, that wasn't far ;-)

**Comment by ToMadoRe** [comment]
But why? This file should exist
https://github.com/strands-project/v4r/blob/1.0.10/modules/recognition/include/v4r/recognition/mesh_source.h

**Comment by marc-hanheide** [comment]
Hah! Found it:
 Look at the [build log](https://lcas.lincoln.ac.uk/jenkins/job/ros-indigo-v4r_binarydeb_trusty_amd64/16/consoleFull) of V4R 1.0.10:

```
-- Module v4r_tomgine disabled because assimp dependency can't be resolved!
-- Module v4r_recognition disabled because v4r_tomgine dependency can't be resolved!
```

It has never created any recognition modules

**Comment by marc-hanheide** [comment]
I.e. our current V4R is a cripple

**Comment by marc-hanheide** [comment]
the file exists in the source tree, but never got installed because recognition wasn't build

**Comment by ToMadoRe** [comment]
Good catch... Well, then it's probably best to remove Tomgine for now, which fails due to some Assimp issue. We have to disable object classification then, but the rest should work.

We are working on a new sort of Tomgine which is compatible with the current Debian version of Assimp. This will take a few more days though.

**Comment by marc-hanheide** [comment]
your call... let me know if you want to re-release

**Comment by ToMadoRe** [comment]
Ok, I created a new V4R branch (https://github.com/strands-project/v4r/tree/remove_tomgine)... we still need to add a CATKIN_IGNORE for the object_classifier, but otherwise this should fix this issue for now.

**Comment by marc-hanheide** [comment]
please open a PR form this branch to have it tested. we should merge it, so to have a working V4R release again, once the PR builds. You can later revert this commit when you want to put tomgine back in place.

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
sorry, triggered the re-test to early

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
still a problem:

```
[ 87%] Building CXX object monitored_vcs/object_classifier/CMakeFiles/object_classifier_node.dir/src/global_nn_classifier_ros.cpp.o
In file included from /var/lib/jenkins/workspace/pr-indigo-v4r_ros_wrappers/monitored_vcs/object_classifier/src/global_nn_classifier_ros.cpp:20:0:
/opt/ros/indigo/include/v4r/recognition/mesh_source.h:23:41: fatal error: v4r/tomgine/tgTomGineThread.h: No such file or directory
 #include <v4r/tomgine/tgTomGineThread.h>
```

**Pull request merged**
